---
#  https://developers.home-assistant.io/docs/add-ons/configuration#add-on-dockerfile
build_from:
  aarch64: "ghcr.io/home-assistant/aarch64-base:3.16"
  amd64: "ghcr.io/home-assistant/amd64-base:3.16"

labels:
  org.opencontainers.image.title: "SBFspot for Home Assistant"
  org.opencontainers.image.description: "SBFspot Bluetooth add-ons."
  org.opencontainers.image.source: "https://github.com/timlaing%2Fsbfspot-ha-addon"
  org.opencontainers.image.licenses: "Apache License 2.0"

args:
  TEMPIO_VERSION: "2021.09.0"
